name: maos
description: Makes browsing news a breeze.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 3.0.0+5

environment:
  sdk: ^3.5.4

dependencies:
  animated_snack_bar: ^0.4.0
  card_loading: ^0.3.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.2.1
  fpdart: ^1.1.1
  get_it: ^8.0.2
  http: ^1.1.0
  iconsax_plus: ^1.0.0
  image_picker: ^1.0.1
  intl: ^0.20.1
  page_transition: ^2.0.9
  supabase_flutter: ^2.8.1

dev_dependencies:
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/navicon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/PlusJakartaSans-Semibold.ttf
